### ISSUE TITLE
hidden flyout errors

### ISSUE THREAD

**Issue by gleborgne** [winjs/winjs#1494]
In some of our applications, we have an error triggered by hidden Flyout when screen resizes.

The following function got triggered but _currentPosition is undefined

_checkScrollPosition: function Flyout_checkScrollPosition(showing) {
                    if (this.hidden && !showing) {
                        return;
                    }

                    // May need to adjust top by viewport offset
                    if (this._currentPosition.top < 0) {
                        // Need to attach to bottom
                        this._element.style.bottom = _Overlay._Overlay._keyboardInfo._visibleDocBottomOffset + "px";
                        this._element.style.top = "auto";
                    } else {
                        // Normal, attach to top
                        this._element.style.top = this._currentPosition.top + "px";
                        this._element.style.bottom = "auto";
                    }
                }

**Comment by jdalton** [comment]
Can you point to the file you're seeing the file/function you're having issues with?

**Comment by convey-gilbert** [comment]
SCRIPT5007: Unhandled exception at line 41368, column 21 ui.js
0x800a138f - JavaScript runtime error: Unable to get property 'top' of undefined or null reference

the reason is: 
_currentPosition is not defined in Flyout object

I would suggest the following work-around:

                _checkScrollPosition: function Flyout_checkScrollPosition(showing) {
                    if (this.hidden && !showing) {
                        return;
                    }
                    // GS 2015-10-14: hidden flyout errors #1494 
                    if (typeof this._currentPosition != 'undefined') {
                        // May need to adjust top by viewport offset
                        if (this._currentPosition.top < 0) {
                            // Need to attach to bottom
                            this._element.style.bottom = _Overlay._Overlay._keyboardInfo._visibleDocBottomOffset + "px";
                            this._element.style.top = "auto";
                        } else {
                            // Normal, attach to top
                            this._element.style.top = this._currentPosition.top + "px";
                            this._element.style.bottom = "auto";
                        }
                    }
                },

                // AppBar flyout animations
                _flyoutAnimateIn: function Flyout_flyoutAnimateIn() {
                    if (this._keyboardMovedUs) {
                        return this._baseAnimateIn();
                    } else {
                        this._element.style.opacity = 1;
                        this._element.style.visibility = "visible";
                        return Animations.showPopup(this._element, 
                            // GS 2015-10-14: hidden flyout errors #1494 - follow up error
                            (typeof this._currentPosition != 'undefined') ? this._currentPosition.animOffset : 0);
                    }
                },

**Comment by jackhand** [comment]
Has there been any progress in this issue? I cannot use the latest version of WinJS because of this issue. I'm forced to use an older version 4.0.1. Perhaps there is a clue as to why version 4.4.0 sees this issue and version 4.0.1 does not.

I reported my observations on this issue elsewhere before I found that it had already been reported:
https://github.com/winjs/winjs/issues/1623

**Comment by jackhand** [comment]
@AmazingJaze were you able to find anything on this?

**Comment by llongley** [comment]
I believe this should be fixed now.

**Comment by micksatana** [comment]
Still have this problem in WinJS 4.4.0

Steps to reproduce in my case.
1. Debug app
2. Use mouse to resize window width to less than 1047 px
3. Close the app
4. Run debug again so it opens with the width 1047px
5. App crashed with this error

> Unhandled exception at line 41342, column 20 in ms-appx://5531951f-067b-42ba-81c6-f42799f13314/WinJS/js/ui.js
> 
> 0x800a138f - JavaScript runtime error: Unable to get property 'top' of undefined or null reference
> 
> If there is a handler for this exception, the program may be safely continued.

Not sure whether because, at width lower than 1047px, I have some component overflow and required scroll so it causes the _checkScrollPosition() error during start-up the app.
